### ISSUE TITLE
Error running `infra:deploy` if the pulumi CLI is not up to date

### ISSUE THREAD

**Issue by vernig** [twilio-infra-as-code/plugin-twilio-infra#4]
If the Pulumi CLI is not up to date, it's printing out a warning. Usually this should not stop the execution of the command, but it does if called from the plugin: 

```shell
twilio infra:deploy 
(node:13865) UnhandledPromiseRejectionWarning: TwilioCliError: Error running Pulumi CLI.
Make sure the Pulumi CLI is installed
TwilioCliError: warning: A new version of Pulumi is available. To upgrade from version '2.21.1' to '2.21.2', run 
   $ curl -sSL https://get.pulumi.com | sh
or visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.

    at checkPulumi (/Users/twilio/dev/major-devops/plugin-twilio-infra-kaique/src/utils.js:142:11)
    at async runPulumiCommand (/Users/twilio/dev/major-devops/plugin-twilio-infra-kaique/src/utils.js:161:21)
(node:13865) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13865) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
The reason for that is that probably in this line: https://github.com/twilio-infra-as-code/plugin-twilio-infra/blob/30efd9a8d57b1d3488fbbe7215d978d5f45e117d/src/utils.js#L145

That needs a refactor.

**Comment by vernig** [comment]
Closed with PR #11
